version: 2
jobs:
  build_linux:
    machine: true
    steps:
    - checkout
    # Build the image
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t arnislielturks/slikenet-nat-server:$CIRCLE_BUILD_NUM .
    - run: docker push arnislielturks/slikenet-nat-server:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build:
    jobs:
    - build_linux